Attempts day3
Fails to compile with:

    Checking advent-of-code-2020 v0.1.0 (/zoom/users/hufman/Projects/advent-of-code-2020)
error[E0106]: missing lifetime specifier
  --> src/day3.rs:58:1
   |
58 | #[aoc(day3, part1)]
   | ^ expected named lifetime parameter
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider introducing a named lifetime parameter
   |
58 | #<'a>[aoc(day3, part1)]<'a>
   | ^^^^^                  ^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: could not compile `advent-of-code-2020`

To learn more, run the command again with --verbose.
An error occurs : cargo build failed with code 101